export const TEMPLATE_IDS = [
  "ProductDemo",
  "ProductDemoVertical",
  "Minimalist",
  "DynamicSocial",
  "SplitScreen",
  "LogoTemplate",
  "PhoneShowcase",
  "BentoGrid",
  "AppleExplodedView",
  "ComparisonSlider",
  "LiquidMorph",
  "SocialProofCarousel",
  "Top5Countdown",
  "UGCCallout",
  "PaperPop",
  "SimulatedUIWalkthrough",
  "DynamicDataDashboard",
  "MinimalistBlueprint",
  "HolographicHUD",
  "CinematicUnboxing",
  "HighEnergyDrop",
  "InfinityScroll",
  "FeatureBinary",
  "NeonNight",
  "RetroVHS",
  "Glassmorphism",
  "ParallaxDepth",
  "AestheticLookbook",
  "FoodieCloseUp",
  "InteriorShowcase",
  "DailyRoutine",
  "WellnessFlow",
  "MaterialFocus",
  "MainAd",
  "MainAdLandscape",
] as const;

export type TemplateId = (typeof TEMPLATE_IDS)[number];
export type TemplateOrientation = "portrait" | "landscape";
export type TemplateTempo = "calm" | "balanced" | "high-energy";

export type TemplateMetadata = {
  label: string;
  description: string;
  orientation: TemplateOrientation;
  sceneDurationSeconds: number;
  tempo: TemplateTempo;
  orchestrationHint: string;
};

const TEMPLATE_ID_SET = new Set<string>(TEMPLATE_IDS);

export function isTemplateId(value: unknown): value is TemplateId {
  return typeof value === "string" && TEMPLATE_ID_SET.has(value);
}

export const DEFAULT_TEMPLATE_ID: TemplateId = "ProductDemo";

export const TEMPLATE_METADATA: Record<TemplateId, TemplateMetadata> = {
  ProductDemo: {
    label: "Product Showcase (Landscape)",
    description: "Multi-angle feature showcase with focus on specs, details, and premium overlays.",
    orientation: "landscape",
    sceneDurationSeconds: 3.4,
    tempo: "balanced",
    orchestrationHint: "Best for tech products, kitchen appliances, or items where detail and utility are key. Show close-ups of features.",
  },
  ProductDemoVertical: {
    label: "Product Showcase (Vertical)",
    description: "Mobile-optimized feature reveal for social media. Quick cuts and clear CTAs.",
    orientation: "portrait",
    sceneDurationSeconds: 3.2,
    tempo: "balanced",
    orchestrationHint: "Default for standard vertical ads. Highlight 3-4 key product benefits with a punchy end-frame.",
  },
  Minimalist: {
    label: "Editorial Minimalist",
    description: "Luxury visual language with white space, elegant serif typography, and calm motion.",
    orientation: "landscape",
    sceneDurationSeconds: 4.2,
    tempo: "calm",
    orchestrationHint: "Best for luxury fashion, skincare, premium home decor, or artisanal products. Use brief, poetic copy.",
  },
  DynamicSocial: {
    label: "High-Energy Social",
    description: "Vibrant, fast-paced 'TikTok' style with bold overlays, trending aesthetics, and aggressive transitions.",
    orientation: "portrait",
    sceneDurationSeconds: 2.8,
    tempo: "high-energy",
    orchestrationHint: "Best for toys, food/beverage, makeup, or impulse-buy gadgets. Use 'hook' language and scroll-stopping visuals.",
  },
  SplitScreen: {
    label: "Comparison / Narrative",
    description: "Dual-panel logic for showing 'Before/After', 'Problem/Solution', or 'Inside/Outside'.",
    orientation: "landscape",
    sceneDurationSeconds: 3.6,
    tempo: "balanced",
    orchestrationHint: "Best for cleaning products, skin-transformations, or showing two perspectives of the same product.",
  },
  LogoTemplate: {
    label: "Brand Logo Reveal",
    description: "A clean, centered logo animation for brand intro or outro.",
    orientation: "landscape",
    sceneDurationSeconds: 5,
    tempo: "balanced",
    orchestrationHint: "Use for brand identity, intros, or outros. Ensure logo is high resolution.",
  },
  PhoneShowcase: {
    label: "Mobile App Showcase",
    description: "Premium mobile device frame with scrolling interface and floating feature bubbles.",
    orientation: "portrait",
    sceneDurationSeconds: 3.5,
    tempo: "balanced",
    orchestrationHint: "Best for mobile apps, software UX, or responsive websites. Show vertical screen interactions.",
  },
  BentoGrid: {
    label: "Modern Bento Grid",
    description: "Multi-panel tiled layout for showing several features or angles simultaneously.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "high-energy",
    orchestrationHint: "Best for tech gadgets with multiple specs or fashion collections. Highlight 3-4 features per scene.",
  },
  AppleExplodedView: {
    label: "Apple-Style Exploded View",
    description: "Cinematic 3D-like decomposition of product components with detailed spec callouts.",
    orientation: "landscape",
    sceneDurationSeconds: 4.5,
    tempo: "balanced",
    orchestrationHint: "Best for high-end hardware, electronics, or modular products. Use for 'engineering-first' narratives.",
  },
  ComparisonSlider: {
    label: "Live Comparison Slider",
    description: "Dynamic A/B comparison with a sliding handle to reveal transformations or upgrades.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "balanced",
    orchestrationHint: "Best for showing results, before/after transformations, or product upgrades.",
  },
  LiquidMorph: {
    label: "Organic Liquid Morph",
    description: "Fluid, organic transitions between scenes using liquid-simulated SVG filters.",
    orientation: "landscape",
    sceneDurationSeconds: 3.8,
    tempo: "calm",
    orchestrationHint: "Best for cosmetics, beverages, or luxury products emphasizing form and flow.",
  },
  SocialProofCarousel: {
    label: "Social Proof Carousel",
    description: "Rotating cards with customer reviews, star ratings, and product testimonials.",
    orientation: "landscape",
    sceneDurationSeconds: 4.2,
    tempo: "balanced",
    orchestrationHint: "Best for building trust. Show the product alongside positive user feedback and ratings.",
  },
  Top5Countdown: {
    label: "High-Energy Countdown",
    description: "Fast-paced 'Top 5' countdown with bold numbers and quick feature highlights.",
    orientation: "landscape",
    sceneDurationSeconds: 2.5,
    tempo: "high-energy",
    orchestrationHint: "Best for punchy feature lists or countdown-style marketing videos.",
  },
  UGCCallout: {
    label: "UGC Social Frame",
    description: "Simulated social media recording UI with floating emojis and 'REC' indicators.",
    orientation: "portrait",
    sceneDurationSeconds: 3.0,
    tempo: "balanced",
    orchestrationHint: "Best for influencer-style content, testimonials, or organic-looking social ads.",
  },
  PaperPop: {
    label: "Storybook Paper-Pop",
    description: "Isometric 'pop-up' 3D book effect for lifestyle product reveals.",
    orientation: "landscape",
    sceneDurationSeconds: 3.5,
    tempo: "calm",
    orchestrationHint: "Best for lifestyle, toys, or subscription boxes where unboxing or reveal is key.",
  },
  SimulatedUIWalkthrough: {
    label: "Simulated UI Walkthrough",
    description: "Interactive-feel UI demonstration with an animated cursor and clicking effects.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "balanced",
    orchestrationHint: "Best for software products, mobile apps, or web-based services. Highlight specific UI interactions.",
  },
  DynamicDataDashboard: {
    label: "Dynamic Data Dashboard",
    description: "Futuristic data visualization with animated charts, counters, and performance metrics.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "high-energy",
    orchestrationHint: "Best for SaaS, fintech, or any product where 'results' and 'efficiency' are the main selling points.",
  },
  MinimalistBlueprint: {
    label: "Minimalist Blueprint",
    description: "Technical, schematic-style visual with wireframe aesthetics and engineering callouts.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "calm",
    orchestrationHint: "Best for architectural design, industrial hardware, or products emphasizing precision engineering.",
  },
  HolographicHUD: {
    label: "Futuristic Holographic HUD",
    description: "High-tech 'Heads-Up Display' with scanning effects, digital gauges, and an Iron Man feel.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "high-energy",
    orchestrationHint: "Best for cutting-edge tech, automotive, or luxury gadgets with a futuristic USP.",
  },
  CinematicUnboxing: {
    label: "Cinematic Unboxing",
    description: "Slow-motion unboxing experience with focus on textures, packaging, and first-look reveals.",
    orientation: "landscape",
    sceneDurationSeconds: 4.5,
    tempo: "calm",
    orchestrationHint: "Best for luxury ecommerce, hardware launches, or physical products with premium packaging.",
  },
  HighEnergyDrop: {
    label: "High-Energy Drop",
    description: "Fast-paced, bass-boosted cuts with heavy glitches and impact-frame styling.",
    orientation: "portrait",
    sceneDurationSeconds: 2.0,
    tempo: "high-energy",
    orchestrationHint: "Best for sneaker drops, streetwear, or Gen-Z targeted product launches.",
  },
  InfinityScroll: {
    label: "Infinity Scroll Catalog",
    description: "Seamless vertical or horizontal scrolling through a gallery of product variations.",
    orientation: "portrait",
    sceneDurationSeconds: 3.5,
    tempo: "balanced",
    orchestrationHint: "Best for fashion variants, food menus, or product colorways.",
  },
  FeatureBinary: {
    label: "Legacy vs. Next-Gen",
    description: "Side-by-side comparison between 'old' tech and your 'new' solution.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "balanced",
    orchestrationHint: "Best for disruptive products that are replacing an outdated industry standard.",
  },
  NeonNight: {
    label: "Neon Night Mode",
    description: "Cyberpunk-inspired aesthetic with glowing neon borders, scanlines, and high-contrast darks.",
    orientation: "portrait",
    sceneDurationSeconds: 3.5,
    tempo: "high-energy",
    orchestrationHint: "Best for gaming gear, nightlife apps, or urban tech products.",
  },
  RetroVHS: {
    label: "Retro VHS Aesthetic",
    description: "90s nostalgia with tracking artifacts, chromatic aberration, and vintage scanlines.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "calm",
    orchestrationHint: "Best for vintage clothing, lo-fi accessories, or 'nostalgic' tech.",
  },
  Glassmorphism: {
    label: "Glassmorphism Showcase",
    description: "Modern, frosted-glass UI with soft blurs, vibrant gradients, and elegant typography.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "balanced",
    orchestrationHint: "Best for enterprise SaaS, premium apps, or luxury digital services.",
  },
  ParallaxDepth: {
    label: "Parallax Depth Layering",
    description: "3D-feel scene with layered product cutouts moving at different speeds for a deep parallax effect.",
    orientation: "landscape",
    sceneDurationSeconds: 4.5,
    tempo: "balanced",
    orchestrationHint: "Best for complex hardware, layered software stacks, or high-end interiors.",
  },
  AestheticLookbook: {
    label: "Aesthetic Lookbook",
    description: "Beautifully framed, multi-window layout with clean lines and soft, airy transitions.",
    orientation: "portrait",
    sceneDurationSeconds: 4.0,
    tempo: "calm",
    orchestrationHint: "Best for fashion, wellness products, or interior design brands.",
  },
  FoodieCloseUp: {
    label: "Foodie Close-Up",
    description: "Intense macro-shots of food/ingredients with savory transitions and recipe-focused layouts.",
    orientation: "portrait",
    sceneDurationSeconds: 3.5,
    tempo: "balanced",
    orchestrationHint: "Best for restaurants, meal kits, snacks, and gourmet food brands.",
  },
  InteriorShowcase: {
    label: "Interior Showcase",
    description: "Spatial panning and elegant framing for furniture and home goods in a lifestyle context.",
    orientation: "landscape",
    sceneDurationSeconds: 4.5,
    tempo: "calm",
    orchestrationHint: "Best for furniture, home decor, real estate, and interior design products.",
  },
  DailyRoutine: {
    label: "Daily Routine Flow",
    description: "Fast-paced montage of daily utility products used in a consistent habit-building sequence.",
    orientation: "portrait",
    sceneDurationSeconds: 3.0,
    tempo: "high-energy",
    orchestrationHint: "Best for cleaning products, persona care, supplements, and household utilities.",
  },
  WellnessFlow: {
    label: "Wellness & Beauty",
    description: "Soft lighting, organic transitions, and calming aesthetic for beauty and wellness products.",
    orientation: "portrait",
    sceneDurationSeconds: 4.0,
    tempo: "calm",
    orchestrationHint: "Best for skincare, yoga gear, essential oils, and premium spa services.",
  },
  MaterialFocus: {
    label: "Material & Texture",
    description: "Macro-texture reveals focusing on craftsmanship, fabrics, and tactile qualities.",
    orientation: "landscape",
    sceneDurationSeconds: 4.0,
    tempo: "balanced",
    orchestrationHint: "Best for high-end furniture, luxury apparel, and hand-crafted hardware.",
  },
  MainAd: {
    label: "Main Ad Composition",
    description: "System container for multi-template ads. Not for direct orchestration.",
    orientation: "portrait",
    sceneDurationSeconds: 4,
    tempo: "balanced",
    orchestrationHint: "Internal use only.",
  },
  MainAdLandscape: {
    label: "Main Ad Composition (Landscape)",
    description: "System container for multi-template ads in landscape. Not for direct orchestration.",
    orientation: "landscape",
    sceneDurationSeconds: 4,
    tempo: "balanced",
    orchestrationHint: "Internal use only.",
  },
};

export const TEMPLATE_PROMPT_CATALOG: Record<TemplateId, string> = {
  ProductDemo: `${TEMPLATE_METADATA.ProductDemo.description} (${TEMPLATE_METADATA.ProductDemo.orientation}).`,
  ProductDemoVertical: `${TEMPLATE_METADATA.ProductDemoVertical.description} (${TEMPLATE_METADATA.ProductDemoVertical.orientation}).`,
  Minimalist: `${TEMPLATE_METADATA.Minimalist.description} (${TEMPLATE_METADATA.Minimalist.orientation}).`,
  DynamicSocial: `${TEMPLATE_METADATA.DynamicSocial.description} (${TEMPLATE_METADATA.DynamicSocial.orientation}).`,
  SplitScreen: `${TEMPLATE_METADATA.SplitScreen.description} (${TEMPLATE_METADATA.SplitScreen.orientation}).`,
  LogoTemplate: `${TEMPLATE_METADATA.LogoTemplate.description} (${TEMPLATE_METADATA.LogoTemplate.orientation}).`,
  PhoneShowcase: `${TEMPLATE_METADATA.PhoneShowcase.description} (${TEMPLATE_METADATA.PhoneShowcase.orientation}).`,
  BentoGrid: `${TEMPLATE_METADATA.BentoGrid.description} (${TEMPLATE_METADATA.BentoGrid.orientation}).`,
  AppleExplodedView: `${TEMPLATE_METADATA.AppleExplodedView.description} (${TEMPLATE_METADATA.AppleExplodedView.orientation}).`,
  ComparisonSlider: `${TEMPLATE_METADATA.ComparisonSlider.description} (${TEMPLATE_METADATA.ComparisonSlider.orientation}).`,
  LiquidMorph: `${TEMPLATE_METADATA.LiquidMorph.description} (${TEMPLATE_METADATA.LiquidMorph.orientation}).`,
  SocialProofCarousel: `${TEMPLATE_METADATA.SocialProofCarousel.description} (${TEMPLATE_METADATA.SocialProofCarousel.orientation}).`,
  Top5Countdown: `${TEMPLATE_METADATA.Top5Countdown.description} (${TEMPLATE_METADATA.Top5Countdown.orientation}).`,
  PaperPop: `${TEMPLATE_METADATA.PaperPop.description} (${TEMPLATE_METADATA.PaperPop.orientation}).`,
  UGCCallout: `${TEMPLATE_METADATA.UGCCallout.description} (${TEMPLATE_METADATA.UGCCallout.orientation}).`,
  SimulatedUIWalkthrough: `${TEMPLATE_METADATA.SimulatedUIWalkthrough.description} (${TEMPLATE_METADATA.SimulatedUIWalkthrough.orientation}).`,
  DynamicDataDashboard: `${TEMPLATE_METADATA.DynamicDataDashboard.description} (${TEMPLATE_METADATA.DynamicDataDashboard.orientation}).`,
  MinimalistBlueprint: `${TEMPLATE_METADATA.MinimalistBlueprint.description} (${TEMPLATE_METADATA.MinimalistBlueprint.orientation}).`,
  HolographicHUD: `${TEMPLATE_METADATA.HolographicHUD.description} (${TEMPLATE_METADATA.HolographicHUD.orientation}).`,
  CinematicUnboxing: `${TEMPLATE_METADATA.CinematicUnboxing.description} (${TEMPLATE_METADATA.CinematicUnboxing.orientation}).`,
  HighEnergyDrop: `${TEMPLATE_METADATA.HighEnergyDrop.description} (${TEMPLATE_METADATA.HighEnergyDrop.orientation}).`,
  InfinityScroll: `${TEMPLATE_METADATA.InfinityScroll.description} (${TEMPLATE_METADATA.InfinityScroll.orientation}).`,
  FeatureBinary: `${TEMPLATE_METADATA.FeatureBinary.description} (${TEMPLATE_METADATA.FeatureBinary.orientation}).`,
  NeonNight: `${TEMPLATE_METADATA.NeonNight.description} (${TEMPLATE_METADATA.NeonNight.orientation}).`,
  RetroVHS: `${TEMPLATE_METADATA.RetroVHS.description} (${TEMPLATE_METADATA.RetroVHS.orientation}).`,
  Glassmorphism: `${TEMPLATE_METADATA.Glassmorphism.description} (${TEMPLATE_METADATA.Glassmorphism.orientation}).`,
  ParallaxDepth: `${TEMPLATE_METADATA.ParallaxDepth.description} (${TEMPLATE_METADATA.ParallaxDepth.orientation}).`,
  AestheticLookbook: `${TEMPLATE_METADATA.AestheticLookbook.description} (${TEMPLATE_METADATA.AestheticLookbook.orientation}).`,
  FoodieCloseUp: `${TEMPLATE_METADATA.FoodieCloseUp.description} (${TEMPLATE_METADATA.FoodieCloseUp.orientation}).`,
  InteriorShowcase: `${TEMPLATE_METADATA.InteriorShowcase.description} (${TEMPLATE_METADATA.InteriorShowcase.orientation}).`,
  DailyRoutine: `${TEMPLATE_METADATA.DailyRoutine.description} (${TEMPLATE_METADATA.DailyRoutine.orientation}).`,
  WellnessFlow: `${TEMPLATE_METADATA.WellnessFlow.description} (${TEMPLATE_METADATA.WellnessFlow.orientation}).`,
  MaterialFocus: `${TEMPLATE_METADATA.MaterialFocus.description} (${TEMPLATE_METADATA.MaterialFocus.orientation}).`,
  MainAd: "Main Ad Container",
  MainAdLandscape: "Main Ad Container (Landscape)",
};

export function getTemplateIdsForOrientation(orientation: TemplateOrientation): TemplateId[] {
  return TEMPLATE_IDS.filter((id) => TEMPLATE_METADATA[id].orientation === orientation);
}
